services:
  zoonavigator:
    image: elkozmon/zoonavigator:latest
    container_name: zoonavigator
    ports:
      - "9001:9000"  # Expose port 9000 on container as 9001 on the host
    environment:
      ZOOKEEPER_SERVERS: zookeeper1:2181,zookeeper2:2181 # Connect ZooNavigator to Zookeeper instances
      DISABLE_AUTH: "true"  # Disable authentication for ZooNavigator (use cautiously)
    volumes:
      - ../../app-data/zoonavigator/configs:/app/configs  # Mount the configs directory
      - ../../app-data/zoonavigator/volumes:/app/volumes  # Mount the volumes directory
    networks:
      - big-data-network  # Connect to the big-data network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000 || exit 1"]  # Health check using curl
      interval: 30s  # Interval between health checks
      timeout: 10s  # Health check timeout
      retries: 5  # Number of retries before marking the service as unhealthy

networks:
  big-data-network:
    external: true  # Use the existing big-data network